<html>
<head><meta charset="utf-8"><title>error message about &quot;xkcd bot&quot; · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/error.20message.20about.20.22xkcd.20bot.22.html">error message about &quot;xkcd bot&quot;</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="1592570"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/error%20message%20about%20%22xkcd%20bot%22/near/1592570" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jonas F <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/error.20message.20about.20.22xkcd.20bot.22.html#1592570">(Jun 13 2023 at 21:00)</a>:</h4>
<p>I'm self hosting a server and recently upgraded to 7.0. Last night I got an email with the following error message about the "xkcd bot" which I haven't done anything with, and I don't think any other user has. I guess I can just ignore it, but I thought I let you know:</p>
<div class="codehilite"><pre><span></span><code>Traceback (most recent call last):
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/django/core/handlers/exception.py&quot;, line 55, in inner
    response = get_response(request)
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/django/core/handlers/base.py&quot;, line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/request.py&quot;, line 459, in _wrapped_req_func
    return_value = req_func(request, *args, **kwargs)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/views/documentation.py&quot;, line 322, in integration_doc
    doc_html_str = render_markdown_path(integration.doc, context, integration_doc=True)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/cache.py&quot;, line 797, in wrapper
    return user_function(*new_args, **kwargs)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/cache.py&quot;, line 764, in __call__
    return self.function(*args, **kwargs)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/cache.py&quot;, line 816, in wrapper
    return user_function(*new_args, **new_kwargs)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/templates.py&quot;, line 173, in render_markdown_path
    html = md_engine.convert(markdown_string)
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/markdown/core.py&quot;, line 258, in convert
    newRoot = treeprocessor.run(root)
  File &quot;/home/zulip/deployments/2023-06-06-00-46-28/./zerver/lib/markdown/static.py&quot;, line 29, in run
    img.set(&quot;src&quot;, staticfiles_storage.url(url[len(&quot;/static/&quot;) :]))
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py&quot;, line 203, in url
    return self._url(self.stored_name, name, force)
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py&quot;, line 182, in _url
    hashed_name = hashed_name_func(*args)
  File &quot;/srv/zulip-venv-cache/12a6b0b3c715a99547489039de2d978c2cc15621/zulip-py3-venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py&quot;, line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for &#39;generated/bots/xkcd/assets/xkcd-help.png&#39;


Deployed code:
- git: None
- ZULIP_VERSION: 7.0


Request info:
- path: /integrations/doc-html/xkcd
- GET: {}
- REMOTE_ADDR: &quot;87.250.224.234&quot;
- QUERY_STRING: &quot;&quot;
- SERVER_NAME: &quot;&quot;
</code></pre></div>



<a name="1592575"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/error%20message%20about%20%22xkcd%20bot%22/near/1592575" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Cyphase <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/error.20message.20about.20.22xkcd.20bot.22.html#1592575">(Jun 13 2023 at 21:06)</a>:</h4>
<p>See <a class="stream-topic" data-stream-id="9" href="/#narrow/stream/9-issues/topic/http.20500.20in.20xkcd.20bot.20docs">#issues &gt; http 500 in xkcd bot docs</a>.</p>



<a name="1593190"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/error%20message%20about%20%22xkcd%20bot%22/near/1593190" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alex Vandiver <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/error.20message.20about.20.22xkcd.20bot.22.html#1593190">(Jun 14 2023 at 18:28)</a>:</h4>
<p><span class="user-mention" data-user-id="17356">@Jonas F</span>: You can safely ignore this.  This is <a href="https://github.com/zulip/zulip/pull/25888">#25888</a> -- it's caused by someone (or some bot) hitting <code>/integrations/docs/xkcd</code> on your server.</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>