<html>
<head><meta charset="utf-8"><title>Error in update analystics count · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html">Error in update analystics count</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="784460"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784460" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> niels <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784460">(Sep 02 2019 at 09:32)</a>:</h4>
<p>With 2.0.4 there is a hourly working cron-job /home/zulip/deployments/current/manage.py update_analytics_counts. It's called via /etc/cron.d. I have no idea what it does. How ever I get every how a new mail about a failure.</p>
<div class="codehilite"><pre><span></span>Traceback (most recent call last):
  File &quot;/home/zulip/deployments/current/manage.py&quot;, line 46, in &lt;module&gt;
    execute_from_command_line(sys.argv)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py&quot;, line 364, in execute_from_command_line
    utility.execute()
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/__init__.py&quot;, line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py&quot;, line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zulip-py3-venv/lib/python3.6/site-packages/django/core/management/base.py&quot;, line 330, in execute
    output = self.handle(*args, **options)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/analytics/management/commands/update_analytics_counts.py&quot;, line 49, in handle
    self.run_update_analytics_counts(options)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/analytics/management/commands/update_analytics_counts.py&quot;, line 90, in run_update_analytics_counts
    send_analytics_to_remote_server()
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zerver/lib/remote_server.py&quot;, line 138, in send_analytics_to_remote_server
    send_to_push_bouncer(&quot;POST&quot;, &quot;server/analytics&quot;, request)
  File &quot;/export/home/zulip/deployments/2019-08-29-19-05-09/zerver/lib/remote_server.py&quot;, line 75, in send_to_push_bouncer
    raise JsonableError(msg)
zerver.lib.exceptions.JsonableError: Invalid data.
</pre></div>


<p>Any suggestions?</p>



<a name="784520"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784520" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784520">(Sep 03 2019 at 01:38)</a>:</h4>
<p><span class="user-mention" data-user-id="11001">@niels</span> that's definitely a bug.  I'll just do a quick fix for it.</p>



<a name="784525"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784525" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784525">(Sep 03 2019 at 01:48)</a>:</h4>
<p><a href="https://github.com/zulip/zulip/commit/70c513a64007c7339cce23ec05a99e9e46400574" target="_blank" title="https://github.com/zulip/zulip/commit/70c513a64007c7339cce23ec05a99e9e46400574">70c513a64007c7339cce23ec05a99e9e46400574</a>; you should just need the code change (not the test).</p>



<a name="784558"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784558" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> niels <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784558">(Sep 03 2019 at 07:15)</a>:</h4>
<p><span class="user-mention" data-user-id="7">@Tim Abbott</span> Thanks for the quick response, but can you explain, what the function does? What data was sent to the pushserver and why?<br>
Sometimes the push-notification fails, is it possible that it is the same issue?</p>



<a name="784572"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784572" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> niels <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784572">(Sep 03 2019 at 09:11)</a>:</h4>
<p>I patched the file. How ever I still get an email:</p>
<div class="codehilite"><pre><span></span>2019-09-03 09:05:07.556 WARN [] Invalid data.
</pre></div>



<a name="784654"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784654" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784654">(Sep 03 2019 at 17:14)</a>:</h4>
<p><span class="user-mention" data-user-id="11001">@niels</span> do you get an email, or just log entries?  Zulip's default configuration should only send emails on ERROR, not WARN.</p>



<a name="784711"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784711" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> niels <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784711">(Sep 03 2019 at 19:47)</a>:</h4>
<p>The program logs to stdout and  cron sends email if a program writes to stdout. So I get an email.</p>



<a name="784712"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784712" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784712">(Sep 03 2019 at 20:19)</a>:</h4>
<p><span class="user-mention" data-user-id="11001">@niels</span> ahh, OK, I see.  Try doing <code>logging.debug</code> instead?</p>



<a name="784713"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784713" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784713">(Sep 03 2019 at 20:19)</a>:</h4>
<p>I'll do a more involved fix when I have a bit more time.</p>



<a name="784751"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784751" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> niels <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784751">(Sep 04 2019 at 06:17)</a>:</h4>
<p><span class="user-mention" data-user-id="7">@Tim Abbott</span> With debug it seems to work. Can you explain, what this cron job does? And why it's important to run? The send always fail, so it could be only have a good site effect.</p>



<a name="784884"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20update%20analystics%20count/near/784884" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20update.20analystics.20count.html#784884">(Sep 04 2019 at 19:36)</a>:</h4>
<p><span class="user-mention" data-user-id="11001">@niels</span> this is <a href="https://zulip.readthedocs.io/en/latest/production/mobile-push-notifications.html#submitting-statistics" target="_blank" title="https://zulip.readthedocs.io/en/latest/production/mobile-push-notifications.html#submitting-statistics">https://zulip.readthedocs.io/en/latest/production/mobile-push-notifications.html#submitting-statistics</a>.  There's a (as yet not understood) bug that's causing your server's submission to be invalid, which is why it's failing.</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>