<html>
<head><meta charset="utf-8"><title>Error in the login :/ · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html">Error in the login :/</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="387521"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/387521" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#387521">(Dec 14 2017 at 15:41)</a>:</h4>
<p>Hi, I have a problem with Zulip.<br>
When I try to recover an entry password, the notification email arrives and I change the password, but when I enter the page again, an error appears.</p>
<p>Well oops. This one's probably our fault. Sorry about that!</p>
<p>If you'd like, you can drop us to line to let us know what happened.</p>
<p>Thank</p>
<p><em>Alejandro</em></p>



<a name="387790"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/387790" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#387790">(Dec 14 2017 at 17:51)</a>:</h4>
<p>This log</p>
<p>Traceback (most recent call last):<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner<br>
    response = get_response(request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response<br>
    response = self._get_response(request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response<br>
    response = self.process_exception_by_middleware(e, request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response<br>
    response = wrapped_callback(request, *callback_args, **callback_kwargs)<br>
  File "./zerver/views/auth.py", line 445, in login_page<br>
    extra_context=extra_context, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 47, in inner<br>
    return func(*args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper<br>
    return view(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view<br>
    response = view_func(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func<br>
    response = view_func(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 82, in login<br>
    auth_login(request, form.get_user())<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 130, in login<br>
    user_logged_in.send(sender=user.__class__, request=request, user=user)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send<br>
    response = receiver(signal=self, sender=sender, **named)<br>
  File "./zerver/signals.py", line 88, in email_on_new_login<br>
    send_email_to_user('zerver/emails/notify_new_login', user, context=context)<br>
  File "./zerver/lib/send_email.py", line 41, in send_email_to_user<br>
    return send_email(template_prefix, display_email(user), from_email=from_email, context=context)<br>
  File "./zerver/lib/send_email.py", line 37, in send_email<br>
    return mail.send() &gt; 0<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send<br>
    return self.get_connection(fail_silently).send_messages([self])<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages<br>
    sent = self._send(message)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send<br>
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))<br>
  File "/usr/lib/python2.7/smtplib.py", line 751, in sendmail<br>
    raise SMTPDataError(code, resp)<br>
SMTPDataError: (550, '5.7.1 Client does not have permissions to send as this sender')</p>
<p>Request info:<br>
- path: /accounts/login/<br>
- POST: {u'username': [u'<strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong>'], u'csrfmiddlewaretoken': [u'<strong>*</strong><strong>*</strong>'], u'password': [u'<strong>*</strong><strong>*</strong>'], u'button': [u'<strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong>']}<br>
- REMOTE_ADDR: "[u'192.168.235.232']"<br>
- QUERY_STRING: "[u'next=']"<br>
- SERVER_NAME: "[u'']"</p>



<a name="387837"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/387837" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Steve Howell <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#387837">(Dec 14 2017 at 18:28)</a>:</h4>
<p>It looks like the <code>zulip</code> userid on your system is not authorized to use <code>sendmail</code> for some reason.</p>



<a name="387964"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/387964" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#387964">(Dec 14 2017 at 19:08)</a>:</h4>
<blockquote>
<p>It looks like the <code>zulip</code> userid on your system is not authorized to use <code>sendmail</code> for some reason.</p>
</blockquote>
<p>Is there any way to give the zulip user permission again?</p>



<a name="388031"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388031" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388031">(Dec 14 2017 at 19:37)</a>:</h4>
<p>This is a Log:</p>
<p>Error generated by Manuel Soto (<a href="mailto:mcsoto@entel.cl" title="mailto:mcsoto@entel.cl">mcsoto@entel.cl</a>) on comunicate deployment</p>
<p>Traceback (most recent call last):<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner<br>
    response = get_response(request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response<br>
    response = self._get_response(request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response<br>
    response = self.process_exception_by_middleware(e, request)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response<br>
    response = wrapped_callback(request, *callback_args, **callback_kwargs)<br>
  File "./zerver/views/auth.py", line 445, in login_page<br>
    extra_context=extra_context, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 47, in inner<br>
    return func(*args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper<br>
    return view(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view<br>
    response = view_func(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func<br>
    response = view_func(request, *args, **kwargs)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 82, in login<br>
    auth_login(request, form.get_user())<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 130, in login<br>
    user_logged_in.send(sender=user.__class__, request=request, user=user)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send<br>
    response = receiver(signal=self, sender=sender, **named)<br>
  File "./zerver/signals.py", line 88, in email_on_new_login<br>
    send_email_to_user('zerver/emails/notify_new_login', user, context=context)<br>
  File "./zerver/lib/send_email.py", line 41, in send_email_to_user<br>
    return send_email(template_prefix, display_email(user), from_email=from_email, context=context)<br>
  File "./zerver/lib/send_email.py", line 37, in send_email<br>
    return mail.send() &gt; 0<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send<br>
    return self.get_connection(fail_silently).send_messages([self])<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages<br>
    sent = self._send(message)<br>
  File "/home/zulip/deployments/2017-07-10-12-50-49/zulip-venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send<br>
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))<br>
  File "/usr/lib/python2.7/smtplib.py", line 751, in sendmail<br>
    raise SMTPDataError(code, resp)<br>
SMTPDataError: (550, '5.7.1 Client does not have permissions to send as this sender')</p>
<p>Request info:<br>
- path: /accounts/login/<br>
- POST: {u'username': [u'<strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong>'], u'csrfmiddlewaretoken': [u'<strong>*</strong><strong>*</strong>'], u'password': [u'<strong>*</strong><strong>*</strong>'], u'button': [u'<strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong>']}<br>
- REMOTE_ADDR: "[u'192.168.235.232']"<br>
- QUERY_STRING: "[u'next=']"<br>
- SERVER_NAME: "[u'']"</p>



<a name="388033"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388033" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Steve Howell <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388033">(Dec 14 2017 at 19:38)</a>:</h4>
<p>I'm not 100% positive here, but I think this is an error with your email configuration, and not really a Zulip-specific issue.   Are you talking to a MS Exchange server?</p>
<p><a href="https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy" target="_blank" title="https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy">https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy</a></p>



<a name="388034"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388034" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388034">(Dec 14 2017 at 19:39)</a>:</h4>
<p>This is example<br>
su zulip<br>
/home/zulip/deployments/current/manage.py send_test_email <a href="mailto:username@example.com" title="mailto:username@example.com">username@example.com</a></p>
<p>the mail works well</p>
<p><a href="/user_uploads/2/62/GgraI9GwpXwgWbnPg8yJlDsY/test_maikl.pdf" target="_blank" title="test_maikl.pdf">test_maikl.pdf</a></p>



<a name="388037"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388037" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388037">(Dec 14 2017 at 19:42)</a>:</h4>
<blockquote>
<p>I'm not 100% positive here, but I think this is an error with your email configuration, and not really a Zulip-specific issue.   Are you talking to a MS Exchange server?</p>
<p><a href="https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy" target="_blank" title="https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy">https://social.technet.microsoft.com/Forums/exchange/en-US/e763de97-88a1-494d-9841-4f3a466b5604/exchange-550-571-client-does-not-have-permissions-to-send-as-this-sender?forum=exchangesvradminlegacy</a></p>
</blockquote>
<p>Hello Steve</p>
<p>The mail I see that works well, I see that when I do the web password change procedure, I get the email and I can change the password, but when I enter the new password, I get the error indicated</p>



<a name="388042"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388042" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Steve Howell <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388042">(Dec 14 2017 at 19:44)</a>:</h4>
<p>If your SMTP passwords changed, you may need to edit <code>/etc/zulip/zulip-secrets.conf</code>.</p>



<a name="388055"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388055" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388055">(Dec 14 2017 at 19:55)</a>:</h4>
<blockquote>
<p>If your SMTP passwords changed, you may need to edit <code>/etc/zulip/zulip-secrets.conf</code>.</p>
</blockquote>
<p>hello, as I say, the emails arrive when I request password change (with this valid the SMTP account of mail no?) I can also change the password of the user, but when I login I drop it.</p>



<a name="388069"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388069" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Steve Howell <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388069">(Dec 14 2017 at 20:05)</a>:</h4>
<p>So login notifications use <code>settings.NOREPLY_EMAIL_ADDRESS</code>.  Is it possible that this is misconfigured as <code>noreply@example.com</code>?</p>



<a name="388073"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/388073" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Steve Howell <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#388073">(Dec 14 2017 at 20:07)</a>:</h4>
<p>can you look at <code>/etc/zulip/settings.py</code> and find <code>NOREPLY_EMAIL_ADDRESS</code>?</p>



<a name="389995"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/389995" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Alejandro <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#389995">(Dec 15 2017 at 15:54)</a>:</h4>
<p>Hello</p>
<p>I just built a clean development environment (installed from scratch) to validate SMTP and it works without problems. I can change password and create users. with this I discard the configuration<a href="/user_uploads/2/83/HClZkyKOIM3ZvCJn2Z9iWczk/Error.jpg" target="_blank" title="Error.jpg">Error.jpg</a></p>
<div class="message_inline_image"><a href="/user_uploads/2/83/HClZkyKOIM3ZvCJn2Z9iWczk/Error.jpg" target="_blank" title="Error.jpg"><img src="/user_uploads/2/83/HClZkyKOIM3ZvCJn2Z9iWczk/Error.jpg"></a></div>



<a name="390381"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/390381" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Greg Price <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#390381">(Dec 15 2017 at 19:34)</a>:</h4>
<p><span class="user-mention" data-user-email="geekjavacl@gmail.com" data-user-id="4516">@Alejandro</span> Hello!</p>
<p>Looking at the error message you've pasted above, which is an error coming from your SMTP server, it says "Client does not have permission to send as this sender."</p>
<p>There are a couple of different "From:" addresses that Zulip uses for different types of email. I suspect that what's happening is that the SMTP credentials you've configured Zulip with have permission on your SMTP server to send as one of these addresses, but not all of them.</p>



<a name="390382"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/Error%20in%20the%20login%20%3A//near/390382" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Greg Price <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/Error.20in.20the.20login.20.3A.2F.html#390382">(Dec 15 2017 at 19:35)</a>:</h4>
<p>That would explain why the password-change email is delivered successfully, but you get an error on sending a different email. (Looking through the stack trace in your original message, Zulip is trying to send you a <code>notify_new_login</code> email, to make sure you know about this new login to your account.)</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>