<html>
<head><meta charset="utf-8"><title>SAML auth redirect loop · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/SAML.20auth.20redirect.20loop.html">SAML auth redirect loop</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="1054267"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/SAML%20auth%20redirect%20loop/near/1054267" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> cap <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/SAML.20auth.20redirect.20loop.html#1054267">(Nov 02 2020 at 12:47)</a>:</h4>
<p>Greetings, I'm using SAML (Keycloak) for user authentication.<br>
So far I've setup the auth and am also forwarded to the idp, but on redirect to zulip I'm find myself on the sso login page again.</p>
<p>The auth.log says the following:<br>
<code>2020-11-02 10:57:52.360 INFO [zulip.auth.saml] /complete/saml/: No valid IdP as issuer of the SAMLResponse.</code><br>
But Keycloak says it authenticated me successful.</p>
<p>I was forced by Keycloak to provide a "Valid Redirect URI" but don't know what to put there, so I used<br>
<code>https://zulip.dm.cap.pink/complete/saml/</code><br>
If no URI provided the authentication fails.</p>
<p>The config I used in settings.py is in the following pastebin<br>
<a href="https://paste.debian.net/hidden/b2b88957/">https://paste.debian.net/hidden/b2b88957/</a></p>
<p>Do you have an idea what I did wrong?<br>
Thank you for your attention.</p>



<a name="1054718"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/SAML%20auth%20redirect%20loop/near/1054718" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Mateusz Mandera <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/SAML.20auth.20redirect.20loop.html#1054718">(Nov 02 2020 at 20:16)</a>:</h4>
<p><span class="user-mention" data-user-id="17716">@cap</span> Like  in <a href="#narrow/stream/31-production-help/topic/SAML.3A.20Issuer.20of.20the.20Assertion.20not.20found.20or.20multiple/near/1040963">https://chat.zulip.org/#narrow/stream/31-production-help/topic/SAML.3A.20Issuer.20of.20the.20Assertion.20not.20found.20or.20multiple/near/1040963</a> in your case I would also recommend manually investgating the SAMLResponse for any irregularities (and the declared Issuers ) so that we can see if that can be causing the error</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>