<html>
<head><meta charset="utf-8"><title>zulip 2.1.7, django 47 memcached error continued · production help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://rht.github.io/czo-archive/stream/31-production-help/index.html">production help</a></h2>
<h3>Topic: <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html">zulip 2.1.7, django 47 memcached error continued</a></h3>

<hr>

<base href="https://chat.zulip.org">

<head><link href="https://rht.github.io/czo-archive/style.css" rel="stylesheet"></head>

<a name="918231"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918231" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> mouk <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918231">(Jun 29 2020 at 07:38)</a>:</h4>
<p>We saw regular django 47 memcached errors on our zulip 2.1 (debian 10) installation and expected them to disappear after updating to latest zulip 2.1.7. We upgraded saturday, and today it happened again:</p>
<div class="codehilite"><pre><span></span><code>Error generated by Anonymous user (not logged in) on zulip deployment

Traceback (most recent call last):
  File &quot;/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py&quot;, line 202, in _get_session
    return self._session_cache
AttributeError: &#39;SessionStore&#39; object has no attribute &#39;_session_cache&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/python3.7/site-packages/django_pylibmc/memcached.py&quot;, line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File &quot;/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/python3.7/site-packages/django/core/cache/backends/memcached.py&quot;, line 79, in get
    val = self._cache.get(key)
pylibmc.Error: error 31 from memcached_get(:1:django.contrib.sessions.cache): (0x561a972d8bf0) A TIMEOUT OCCURRED, No active_fd were found,  host: 127.0.0.1:11211 -&gt; libmemcached/io.cc:259

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/python3.7/site-packages/django_pylibmc/memcached.py&quot;, line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x561a972d8bf0) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: 127.0.0.1:11211 -&gt; libmemcached/connect.cc:720


Deployed code:
- ZULIP_VERSION: 2.1.7
- version: 2.1.7
</code></pre></div>


<p>There are always only two notifications in a row, and usually it happens only once a day, around a whole hour (sample times: 5:56 PM, 8:57 AM, 9:00 AM) but there are also days that they don't show up. The zulip system itself seems to work fine.</p>
<p>Is there something specific to our installation (it's a very regular install, using the regular procedure from »  Zulip in Production » Production Installation)</p>
<p>Are we the only ones still seeing this in 2.1.7?</p>



<a name="918233"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918233" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918233">(Jun 29 2020 at 07:52)</a>:</h4>
<p><span class="user-mention" data-user-id="16223">@mouk</span> I'm getting these since upgrading from 2.1.4-0 to 2.1.7-0 a couple of days ago. I get these errors every couple of minutes.</p>



<a name="918234"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918234" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918234">(Jun 29 2020 at 07:53)</a>:</h4>
<p>(I'm using the docker deploy. Also a regular install.)</p>



<a name="918235"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918235" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> mouk <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918235">(Jun 29 2020 at 07:55)</a>:</h4>
<p>Every couple of minutes. That's different. And your installation is also working fine?</p>



<a name="918236"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918236" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918236">(Jun 29 2020 at 07:58)</a>:</h4>
<p>It seems to be. At least I didn't notice anything that's not working yet.</p>



<a name="918237"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918237" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918237">(Jun 29 2020 at 08:03)</a>:</h4>
<p>In my case, the problem might have been that I had to adjust memcached (since the default username changed): <a href="https://github.com/zulip/zulip/pull/15462">https://github.com/zulip/zulip/pull/15462</a></p>



<a name="918238"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918238" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918238">(Jun 29 2020 at 08:05)</a>:</h4>
<p>Your error message is different in some details though, so this probably a different error.</p>



<a name="918239"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918239" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918239">(Jun 29 2020 at 08:05)</a>:</h4>
<p>Sorry for missing the difference when comparing the errors...</p>



<a name="918240"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918240" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> mouk <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918240">(Jun 29 2020 at 08:07)</a>:</h4>
<p>But are you saying you actually changed the username in settings.py? With me it's the default (so I guess  this changed to "zulip@localhost" since 2.1.7)</p>



<a name="918241"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918241" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918241">(Jun 29 2020 at 08:09)</a>:</h4>
<p>No, but for the docker setup, the username is explicitly set for memcached itself (not for zulip), and that needed to be updated to what zulip is now using.</p>



<a name="918242"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918242" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> mouk <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918242">(Jun 29 2020 at 08:11)</a>:</h4>
<p>right, thanks.</p>



<a name="918576"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918576" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918576">(Jun 29 2020 at 18:39)</a>:</h4>
<p><span class="user-mention" data-user-id="16386">@Felix Fontein</span> just to check, was the issue that you needed to update your <code>docker-compose.yml</code> for changes we made in the 2.1.7 release of <code>docker-zulip</code>, or do you think there are issues with our current <code>docker-compose.yml</code>?</p>



<a name="918797"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918797" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Felix Fontein <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918797">(Jun 29 2020 at 19:46)</a>:</h4>
<p><span class="user-mention" data-user-id="7">@Tim Abbott</span> thanks for checking! This issue was because I converted the docker-compose.yml to an Ansible script (to avoid using docker-compose), and I didn't first check whether the docker-compose.yml in <a href="https://github.com/zulip/docker-zulip/">https://github.com/zulip/docker-zulip/</a> changed.</p>



<a name="918799"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/918799" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#918799">(Jun 29 2020 at 19:46)</a>:</h4>
<p>OK, great, good to know!</p>



<a name="943018"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943018" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roman Bannack <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943018">(Jul 17 2020 at 22:50)</a>:</h4>
<p>I upgraded from 2.1.3 to 2.1.7 (Dockerhub doesn't have a 3.0 image as for now) and now I'm bombarded with these memcached error 47 emails. Got 1000+ mails within one day. <span aria-label="sad" class="emoji emoji-2639" role="img" title="sad">:sad:</span> </p>
<p>What did I do?</p>
<ul>
<li>Upgrade Docker-Zulip to 2.1.7</li>
<li>Added the one line to docker-compose.yml that was introduced with 2.1.7:</li>
</ul>
<div class="codehilite"><pre><span></span><code>echo &quot;zulip@localhost::$$MEMCACHED_PASSWORD&quot; &gt;&gt; &quot;$$MEMCACHED_SASL_PWDB&quot;
</code></pre></div>


<ul>
<li>Restarted the stack.</li>
</ul>
<p>That's all. Zulip works fine, but the flood of emails keeps coming in.</p>
<p>In the meantime, my hosting provider rebooted the VS. Don't know if that's an issue.</p>
<p>Is there anything I can do?</p>
<p>I can only use Zulip with Docker since I'm bound to an OpenVZ VS where a normal installation won't run.</p>
<p>Any hint appreciated!</p>
<div class="codehilite"><pre><span></span><code>version: &#39;2&#39;
services:
  database:
    image: &#39;zulip/zulip-postgresql:10&#39;
    environment:
      POSTGRES_DB: &#39;zulip&#39;
      POSTGRES_USER: &#39;zulip&#39;
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: &#39;******obscured******&#39;
    volumes:
      - &#39;/opt/docker/zulip/postgresql/data:/var/lib/postgresql/data:rw&#39;
    restart: always
  memcached:
    image: &#39;memcached:alpine&#39;
    command:
      - &#39;sh&#39;
      - &#39;-euc&#39;
      - |
        echo &#39;mech_list: plain&#39; &gt; &quot;$$SASL_CONF_PATH&quot;
        echo &quot;zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD&quot; &gt; &quot;$$MEMCACHED_SASL_PWDB&quot;
        echo &quot;zulip@localhost::$$MEMCACHED_PASSWORD&quot; &gt;&gt; &quot;$$MEMCACHED_SASL_PWDB&quot;
        exec memcached -S
    environment:
      SASL_CONF_PATH: &#39;/home/memcache/memcached.conf&#39;
      MEMCACHED_SASL_PWDB: &#39;/home/memcache/memcached-sasl-db&#39;
      MEMCACHED_PASSWORD: &#39;******obscured******&#39;
    restart: always
  rabbitmq:
    image: &#39;rabbitmq:3.7.7&#39;
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: &#39;zulip&#39;
        RABBITMQ_DEFAULT_PASS: &#39;******obscured******&#39;
    volumes:
      - &#39;/opt/docker/zulip/rabbitmq:/var/lib/rabbitmq:rw&#39;
  redis:
    image: &#39;redis:alpine&#39;
    command:
      - &#39;sh&#39;
      - &#39;-euc&#39;
      - |
        echo &quot;requirepass &#39;$$REDIS_PASSWORD&#39;&quot; &gt; /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: &#39;******obscured******&#39;
    volumes:
      - &#39;/opt/docker/zulip/redis:/data:rw&#39;
    restart: always
  zulip:
    image: &#39;zulip/docker-zulip:2.1.7-0&#39;
#    build:
#      context: .
#      args:
        # Change these if you want to build zulip from a different repo/branch
#        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
#        ZULIP_GIT_REF: 2.1.7
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    ports:
      - &#39;10080:80&#39;
      - &#39;10443:443&#39;
#    expose:
#      - 443
    environment:
      DB_HOST: &#39;database&#39;
      DB_HOST_PORT: &#39;5432&#39;
      DB_USER: &#39;zulip&#39;
      SSL_CERTIFICATE_GENERATION: &#39;self-signed&#39;
      SETTING_MEMCACHED_LOCATION: &#39;memcached:11211&#39;
      SETTING_RABBITMQ_HOST: &#39;rabbitmq&#39;
      SETTING_REDIS_HOST: &#39;redis&#39;
      SECRETS_email_password: &#39;******obscured******&#39;
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: &#39;******obscured******&#39;
      SECRETS_postgres_password: &#39;******obscured******&#39;
      SECRETS_memcached_password: &#39;******obscured******&#39;
      SECRETS_redis_password: &#39;******obscured******&#39;
      SECRETS_secret_key: &#39;******obscured******&#39;
      SETTING_EXTERNAL_HOST: &#39;******obscured******&#39;
      SETTING_ZULIP_ADMINISTRATOR: &#39;******obscured******&#39;
      SETTING_EMAIL_HOST: &#39;******obscured******&#39;  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: &#39;******obscured******&#39;
      SETTING_EMAIL_PORT: &#39;25&#39;
      # It seems that the email server needs to use ssl or tls and can&#39;t be used without it
      SETTING_EMAIL_USE_SSL: &#39;False&#39;
      SETTING_EMAIL_USE_TLS: &#39;True&#39;
      ZULIP_AUTH_BACKENDS: &#39;EmailAuthBackend&#39;
      SETTING_USE_X_FORWARDED_HOST: &#39;True&#39;
      SETTING_ALLOWED_HOSTS: &quot;[&#39;*&#39;, &#39;0.0.0.0&#39;]&quot;
      DISABLE_HTTPS: &quot;True&quot;

      # Settings for custom Terms and Privacy Policy
      SETTING_TERMS_OF_SERVICE: &#39;/data/terms.md&#39;
      SETTING_PRIVACY_POLICY: &#39;/data/privacy.md&#39;

      # Settings für Incoming E-Mail (Polling)
      SETTING_EMAIL_GATEWAY_PATTERN: &quot;******obscured******&quot;
      SETTING_EMAIL_GATEWAY_LOGIN: &quot;******obscured******&quot;
      SETTING_EMAIL_GATEWAY_IMAP_SERVER: &quot;******obscured******&quot;
      SETTING_EMAIL_GATEWAY_IMAP_PORT: &quot;******obscured******&quot;
      SETTING_EMAIL_GATEWAY_IMAP_FOLDER: &quot;INBOX&quot;
      SECRETS_email_gateway_password: &quot;******obscured******&quot;

      # Settings für JITSI
      SETTING_JITSI_SERVER_URL: &quot;******obscured******&quot;

      # Uncomment this when configuring the mobile push notifications service
      SETTING_PUSH_NOTIFICATION_BOUNCER_URL: &#39;https://push.zulipchat.com&#39;
    volumes:
      - &#39;/opt/docker/zulip/zulip:/data:rw&#39;
    ulimits:
      nofile:
        soft: 40000
        hard: 50000
    restart: unless-stopped
</code></pre></div>



<a name="943097"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943097" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943097">(Jul 18 2020 at 00:51)</a>:</h4>
<p><span class="user-mention" data-user-id="14475">@Roman Bannack</span> the issue is almost certainly that memcached authentication is broken.</p>



<a name="943098"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943098" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943098">(Jul 18 2020 at 00:51)</a>:</h4>
<p>In theory this change is what you needed to do, but I see you have that:<br>
<a href="https://github.com/zulip/docker-zulip/commit/0810e2ba67ddf34f59f619cb07c60a40c08de235">https://github.com/zulip/docker-zulip/commit/0810e2ba67ddf34f59f619cb07c60a40c08de235</a></p>



<a name="943099"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943099" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943099">(Jul 18 2020 at 00:52)</a>:</h4>
<p>But I guess I'd recommend double-checking that you have the same credentials used for memcached authentication in all places.</p>



<a name="943100"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943100" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943100">(Jul 18 2020 at 00:52)</a>:</h4>
<p>(An unfortunate aspect of memcached specifically being broken is that its exceptions have a random value in them that avoids our rate-limiting of a given exception)</p>



<a name="943312"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943312" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roman Bannack <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943312">(Jul 18 2020 at 11:47)</a>:</h4>
<p><span class="user-mention" data-user-id="7">@Tim Abbott</span> What I noticed is that the error is reported for some other deployment than "current":</p>
<div class="codehilite"><pre><span></span><code>Logger django.pylibmc, from module django_pylibmc.memcached line 146:
Error generated by Anonymous user (not logged in) on 37b2d2122a11 deployment

Traceback (most recent call last):
  File &quot;/home/zulip/deployments/2020-06-26-05-15-05/zulip-py3-venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py&quot;, line 202, in _get_session
    return self._session_cache
AttributeError: &#39;SessionStore&#39; object has no attribute &#39;_session_cache&#39;
(...)
Deployed code:
- ZULIP_VERSION: 2.1.7
- version: docker
</code></pre></div>


<p>2020-06-26 is obviously not the date that I upgraded to 2.1.7. Don't know if that's a hint where the problem is.</p>



<a name="943314"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943314" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roman Bannack <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943314">(Jul 18 2020 at 11:49)</a>:</h4>
<p>Other than that, credentials are the same everywhere as passed from <code>docker-compose.yml</code>.</p>



<a name="943317"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/943317" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roman Bannack <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#943317">(Jul 18 2020 at 11:59)</a>:</h4>
<p>There are two different error emails sent, more or less interchanging: <a href="https://pastebin.com/WAteb4n2">one</a> and <a href="https://pastebin.com/hceEaCvb">two</a>. Both say "error 47 from memcached_set (...)" in the subject.</p>



<a name="944718"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/944718" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#944718">(Jul 20 2020 at 03:57)</a>:</h4>
<p><span class="user-mention" data-user-id="699">@Anders Kaseorg</span> do we have a memcached debugging guide?  Maybe we should write one so we can point folks at it for this sort of thing.  Potentially in <code>docs/production/troubleshooting.md</code>?</p>



<a name="945294"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/945294" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Roman Bannack <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#945294">(Jul 20 2020 at 18:45)</a>:</h4>
<p>For the record, just now I found the (my) error in the added <code>zulip@localhost</code>auth line in docker-compose.yml:</p>
<div class="codehilite"><pre><span></span><code>echo &quot;zulip@localhost::$$MEMCACHED_PASSWORD&quot; &gt;&gt; &quot;$$MEMCACHED_SASL_PWDB&quot;
</code></pre></div>


<p>Why did I put in a double colon there in the first place? <span aria-label="cry" class="emoji emoji-1f622" role="img" title="cry">:cry:</span> It turns out this was responsible for Zulip failing to authenticate at memcached (no surprise, of course). Though I imagine I copied+pasted the line when I was updating the file.</p>
<p>Anyhow, thanks all for your patience!</p>



<a name="945407"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/945407" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#945407">(Jul 20 2020 at 21:45)</a>:</h4>
<p>Great, thanks for the follow-up <span class="user-mention" data-user-id="14475">@Roman Bannack</span>! <span aria-label="slight smile" class="emoji emoji-1f642" role="img" title="slight smile">:slight_smile:</span></p>



<a name="945408"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/945408" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Tim Abbott <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#945408">(Jul 20 2020 at 21:45)</a>:</h4>
<p>It's really valuable to learn this sort of mystery was a typo as opposed to some sort of new bug.</p>



<a name="958295"></a>
<h4><a href="https://chat.zulip.org#narrow/stream/31-production%20help/topic/zulip%202.1.7%2C%20django%2047%20memcached%20error%20continued/near/958295" class="zl"><img src="https://rht.github.io/czo-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> guneet narula <a href="https://rht.github.io/czo-archive/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued.html#958295">(Jul 27 2020 at 22:09)</a>:</h4>
<p><span class="user-mention silent" data-user-id="7">Tim Abbott</span> <a href="#narrow/stream/31-production-help/topic/zulip.202.2E1.2E7.2C.20django.2047.20memcached.20error.20continued/near/944718">said</a>:</p>
<blockquote>
<p><span class="user-mention silent" data-user-id="699">Anders Kaseorg</span> do we have a memcached debugging guide?  Maybe we should write one so we can point folks at it for this sort of thing.  Potentially in <code>docs/production/troubleshooting.md</code>?</p>
</blockquote>
<p>Is there a place I can start on debugging this error? I am on 3.0, started getting this error recently, not very often though.</p>



<hr><p>Last updated: Oct 02 2023 at 04:38 UTC</p>
</html>