[
    {
        "content": "<p>I'm trying to import as per the instructions at <a href=\"https://zulip.readthedocs.io/en/latest/production/export-and-import.html\" target=\"_blank\" title=\"https://zulip.readthedocs.io/en/latest/production/export-and-import.html\">https://zulip.readthedocs.io/en/latest/production/export-and-import.html</a></p>\n<p>When I run <code>./manage.py import --destroy-rebuild-database '' /path/to/zulip-export-7sjiwppo/</code> I get this error...</p>\n<div class=\"codehilite\"><pre><span></span>Processing dump: /home/ubuntu/tmp-zulip/zulip-export-7sjiwppo ...\n2018-10-15 16:57:58.452 INFO [] Importing realm dump /home/ubuntu/tmp-zulip/zulip-export-7sjiwppo\n2018-10-15 16:57:58.452 INFO [] Importing realm data from /home/ubuntu/tmp-zulip/zulip-export-7sjiwppo/realm.json\nTraceback (most recent call last):\n  File &quot;./manage.py&quot;, line 25, in &lt;module&gt;\n    execute_from_command_line(sys.argv)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py&quot;, line 364, in execute_from_command_line\n    utility.execute()\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py&quot;, line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py&quot;, line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py&quot;, line 330, in execute\n    output = self.handle(*args, **options)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zerver/management/commands/import.py&quot;, line 85, in handle\n    realm = do_import_realm(path, subdomain)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zerver/lib/import_realm.py&quot;, line 421, in do_import_realm\n    realm = Realm(**data[&#39;zerver_realm&#39;][0])\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/db/models/base.py&quot;, line 555, in __init__\n    _setattr(self, field.name, rel_obj)\n  File &quot;/home/zulip/deployments/2018-10-15-14-57-53/zulip-py3-venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py&quot;, line 216, in __set__\n    self.field.remote_field.model._meta.object_name,\nValueError: Cannot assign &quot;1&quot;: &quot;Realm.signup_notifications_stream&quot; must be a &quot;Stream&quot; instance.\n</pre></div>\n\n\n<p>I'm trying to move from 1.8.1 to 1.8.1 - does anyone have any ideas?</p>",
        "id": 652488,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539626414
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"133\">@Bruce Lewin</span> I recommend upgrading both servers to master first.</p>",
        "id": 652506,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1539631831
    },
    {
        "content": "<p>(There's been a lot of improvements to the export tool in the 1.9 release series)</p>",
        "id": 652507,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1539631847
    },
    {
        "content": "<p>I'm also curious: why are you doing export/import rather than just a database dump?</p>",
        "id": 652508,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1539631863
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"7\">@Tim Abbott</span> thanks Tim... both machines are running git master but I've now hit this error when importing... What would you suggest?</p>\n<div class=\"codehilite\"><pre><span></span>2018-10-16 07:51:44.657 INFO [] Importing realm dump /home/ubuntu/tmp-zulip/zulip-export-z1seotdw\n2018-10-16 07:51:44.658 INFO [] Importing realm data from /home/ubuntu/tmp-zulip/zulip-export-z1seotdw/realm.json\n2018-10-16 07:51:44.938 INFO [] Successfully imported &lt;class &#39;zerver.models.Stream&#39;&gt; from zerver_stream.\nTraceback (most recent call last):\n  File &quot;./manage.py&quot;, line 36, in &lt;module&gt;\n    execute_from_command_line(sys.argv)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py&quot;, line 364, in execute_from_command_line\n    utility.execute()\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/__init__.py&quot;, line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py&quot;, line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zulip-py3-venv/lib/python3.5/site-packages/django/core/management/base.py&quot;, line 330, in execute\n    output = self.handle(*args, **options)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zerver/management/commands/import.py&quot;, line 71, in handle\n    realm = do_import_realm(path, subdomain)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zerver/lib/import_realm.py&quot;, line 705, in do_import_realm\n    logging.info(&quot;Adding to ID map: %s %s&quot; % (item[&#39;id&#39;], get_system_bot(item[&#39;email&#39;]).id))\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zerver/lib/cache.py&quot;, line 166, in func_with_caching\n    val = func(*args, **kwargs)\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zerver/models.py&quot;, line 1787, in get_system_bot\n    return UserProfile.objects.select_related().get(email__iexact=email.strip())\n  File &quot;/home/zulip/deployments/2018-10-16-09-30-55/zulip-py3-venv/lib/python3.5/site-packages/django/db/models/query.py&quot;, line 380, in get\n    self.model._meta.object_name\nzerver.models.DoesNotExist: UserProfile matching query does not exist.\n</pre></div>",
        "id": 652630,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539677621
    },
    {
        "content": "<p>I'm now trying to get zulip going as-is with a fresh installl... I've installed on 16.04 and then upgraded immediately to the <a href=\"https://zulip.readthedocs.io/en/stable/production/maintain-secure-upgrade.html#upgrading-from-a-git-repository\" target=\"_blank\" title=\"https://zulip.readthedocs.io/en/stable/production/maintain-secure-upgrade.html#upgrading-from-a-git-repository\">master git branch</a> but I only get error 503 in the browser... </p>\n<p>I should also add that I'm using LXD and have HA Proxy running to forward requests for <a href=\"http://zulip.mydomain.com\" target=\"_blank\" title=\"http://zulip.mydomain.com\">zulip.mydomain.com</a> to the zulip container...</p>",
        "id": 652632,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539683744
    },
    {
        "content": "<blockquote>\n<p>I'm also curious: why are you doing export/import rather than just a database dump?</p>\n</blockquote>\n<p>I didn't understand the docs (hahaha!) but having now re-read them I ran</p>\n<p><code>zulip@zulip:~$ sudo /usr/local/bin/pg_backup_and_purge</code></p>\n<p>and his this error</p>\n<div class=\"codehilite\"><pre><span></span>Traceback (most recent call last):\n  File &quot;/usr/local/bin/pg_backup_and_purge&quot;, line 20, in &lt;module&gt;\n    def run(args: List[str], dry_run: bool=False) -&gt; str:\nNameError: name &#39;List&#39; is not defined\n</pre></div>\n\n\n<p>hmm....</p>",
        "id": 652633,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539684536
    },
    {
        "content": "<p>To add further to my discoveries...</p>\n<div class=\"codehilite\"><pre><span></span>zulip@zulip:~$ sudo -i\nroot@zulip:~# sudo /usr/local/bin/pg_backup_and_purge.py\n2018-10-16 12:09:07,458 ERROR: Could not invoke psql\nstdout:\nstderror: psql: FATAL:  role &quot;root&quot; does not exist\n</pre></div>",
        "id": 652634,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539684625
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"133\">@Bruce Lewin</span> not relevant to pg backup, but the import command has changed in master; --destroy-rebuild-database has been deprecated</p>",
        "id": 652636,
        "sender_full_name": "Rishi Gupta",
        "timestamp": 1539687867
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"131\">@Rishi Gupta</span> Thanks Rishi, do you know what the new import command is?</p>",
        "id": 652642,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539697450
    },
    {
        "content": "<p>Yeah, it's the same thing just without that flag. I'll update the documentation later today; thanks for the catch.</p>",
        "id": 652665,
        "sender_full_name": "Rishi Gupta",
        "timestamp": 1539706938
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"133\">@Bruce Lewin</span> for the <code>pg_backup</code> thing, it looks like it was incorrectly converted to the Python 3 typing syntax (where the type annotations are in the code itself, not comments).  I'm going to quickly fix that.</p>",
        "id": 652725,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1539713520
    },
    {
        "content": "<p>Fixed in <a href=\"https://github.com/zulip/zulip/commit/98d89b676ddd03e4735eca1d9da9840e03138f24\" target=\"_blank\" title=\"https://github.com/zulip/zulip/commit/98d89b676ddd03e4735eca1d9da9840e03138f24\">98d89b676ddd03e4735eca1d9da9840e03138f24</a>, thanks for the report!</p>",
        "id": 652728,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1539713656
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"7\">@Tim Abbott</span> <span class=\"user-mention\" data-user-id=\"131\">@Rishi Gupta</span> Thanks for the updates guys... I'll check back in a day or two with  an update... hopefully the new import command works!</p>",
        "id": 652780,
        "sender_full_name": "Bruce Lewin",
        "timestamp": 1539716378
    }
]