[
    {
        "content": "<p>Anyone has any ideas what is causing this? It become gradually more and more often the occurance.</p>",
        "id": 1414146,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659450633
    },
    {
        "content": "<div class=\"codehilite\" data-code-language=\"Bash\"><pre><span></span><code>Logger root, from module zerver.worker.queue_processors line <span class=\"m\">379</span>:\nError generated by Anonymous user <span class=\"o\">(</span>not logged <span class=\"k\">in</span><span class=\"o\">)</span> on chat deployment\n\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n File <span class=\"s2\">\"/usr/lib/python3.8/os.py\"</span>, line <span class=\"m\">672</span>, <span class=\"k\">in</span> __getitem__\n   <span class=\"nv\">value</span> <span class=\"o\">=</span> self._data<span class=\"o\">[</span>self.encodekey<span class=\"o\">(</span>key<span class=\"o\">)]</span>\nKeyError: b<span class=\"s1\">'DJANGO_ALLOW_ASYNC_UNSAFE'</span>\n</code></pre></div>",
        "id": 1414147,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659450651
    },
    {
        "content": "<div class=\"codehilite\" data-code-language=\"Bash\"><pre><span></span><code>During handling of the above exception, another exception occurred:\n\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n File <span class=\"s2\">\"/home/zulip/deployments/2022-08-01-19-55-31/zerver/worker/queue_processors.py\"</span>, line <span class=\"m\">314</span>, <span class=\"k\">in</span> do_consume\n   consume_func<span class=\"o\">(</span>events<span class=\"o\">)</span>\n File <span class=\"s2\">\"/home/zulip/deployments/2022-08-01-19-55-31/zerver/worker/queue_processors.py\"</span>, line <span class=\"m\">557</span>, <span class=\"k\">in</span> consume_batch\n   do_update_user_activity<span class=\"o\">(</span>user_profile_id, client_id, query, count, log_time<span class=\"o\">)</span>\n File <span class=\"s2\">\"/home/zulip/deployments/2022-08-01-19-55-31/zerver/decorator.py\"</span>, line <span class=\"m\">946</span>, <span class=\"k\">in</span> wrapped_func\n   <span class=\"nv\">ret</span> <span class=\"o\">=</span> func<span class=\"o\">(</span>*args, **kwargs<span class=\"o\">)</span>\n File <span class=\"s2\">\"/home/zulip/deployments/2022-08-01-19-55-31/zerver/actions/user_activity.py\"</span>, line <span class=\"m\">49</span>, <span class=\"k\">in</span> do_update_user_activity\n   activity.save<span class=\"o\">(</span><span class=\"nv\">update_fields</span><span class=\"o\">=[</span><span class=\"s2\">\"last_visit\"</span>, <span class=\"s2\">\"count\"</span><span class=\"o\">])</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/base.py\"</span>, line <span class=\"m\">806</span>, <span class=\"k\">in</span> save\n   self.save_base<span class=\"o\">(</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/base.py\"</span>, line <span class=\"m\">857</span>, <span class=\"k\">in</span> save_base\n   <span class=\"nv\">updated</span> <span class=\"o\">=</span> self._save_table<span class=\"o\">(</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/base.py\"</span>, line <span class=\"m\">970</span>, <span class=\"k\">in</span> _save_table\n   <span class=\"nv\">updated</span> <span class=\"o\">=</span> self._do_update<span class=\"o\">(</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/base.py\"</span>, line <span class=\"m\">1034</span>, <span class=\"k\">in</span> _do_update\n   <span class=\"k\">return</span> filtered._update<span class=\"o\">(</span>values<span class=\"o\">)</span> &gt; <span class=\"m\">0</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/query.py\"</span>, line <span class=\"m\">885</span>, <span class=\"k\">in</span> _update\n   <span class=\"k\">return</span> query.get_compiler<span class=\"o\">(</span>self.db<span class=\"o\">)</span>.execute_sql<span class=\"o\">(</span>CURSOR<span class=\"o\">)</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py\"</span>, line <span class=\"m\">1783</span>, <span class=\"k\">in</span> execute_sql\n   <span class=\"nv\">cursor</span> <span class=\"o\">=</span> super<span class=\"o\">()</span>.execute_sql<span class=\"o\">(</span>result_type<span class=\"o\">)</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py\"</span>, line <span class=\"m\">1359</span>, <span class=\"k\">in</span> execute_sql\n   <span class=\"nv\">cursor</span> <span class=\"o\">=</span> self.connection.cursor<span class=\"o\">()</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py\"</span>, line <span class=\"m\">26</span>, <span class=\"k\">in</span> inner\n   <span class=\"k\">return</span> func<span class=\"o\">(</span>*args, **kwargs<span class=\"o\">)</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py\"</span>, line <span class=\"m\">284</span>, <span class=\"k\">in</span> cursor\n   <span class=\"k\">return</span> self._cursor<span class=\"o\">()</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py\"</span>, line <span class=\"m\">262</span>, <span class=\"k\">in</span> _cursor\n   <span class=\"k\">return</span> self._prepare_cursor<span class=\"o\">(</span>self.create_cursor<span class=\"o\">(</span>name<span class=\"o\">))</span>\n File <span class=\"s2\">\"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py\"</span>, line <span class=\"m\">17</span>, <span class=\"k\">in</span> inner\n   <span class=\"k\">if</span> not os.environ.get<span class=\"o\">(</span><span class=\"s2\">\"DJANGO_ALLOW_ASYNC_UNSAFE\"</span><span class=\"o\">)</span>:\n File <span class=\"s2\">\"/usr/lib/python3.8/_collections_abc.py\"</span>, line <span class=\"m\">660</span>, <span class=\"k\">in</span> get\n   <span class=\"k\">return</span> self<span class=\"o\">[</span>key<span class=\"o\">]</span>\n File <span class=\"s2\">\"/usr/lib/python3.8/os.py\"</span>, line <span class=\"m\">672</span>, <span class=\"k\">in</span> __getitem__\n   <span class=\"nv\">value</span> <span class=\"o\">=</span> self._data<span class=\"o\">[</span>self.encodekey<span class=\"o\">(</span>key<span class=\"o\">)]</span>\n File <span class=\"s2\">\"/home/zulip/deployments/2022-08-01-19-55-31/zerver/worker/queue_processors.py\"</span>, line <span class=\"m\">360</span>, <span class=\"k\">in</span> timer_expired\n   raise WorkerTimeoutException<span class=\"o\">(</span>self.queue_name, limit, len<span class=\"o\">(</span>events<span class=\"o\">))</span>\nzerver.worker.queue_processors.WorkerTimeoutException: Timed out <span class=\"k\">in</span> user_activity after <span class=\"m\">30</span> seconds processing <span class=\"m\">1</span> events\n\n\nDeployed code:\n- git: <span class=\"m\">6</span>.0-dev-1177-gf2a3236b42\n- ZULIP_VERSION: <span class=\"m\">6</span>.0-dev-1177-gf2a3236b42\n</code></pre></div>",
        "id": 1414149,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659450670
    },
    {
        "content": "<p><a href=\"/user_uploads/2/aa/uBk3axLIzZhikLo4w8ft74pA/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/aa/uBk3axLIzZhikLo4w8ft74pA/image.png\" title=\"image.png\"><img src=\"/user_uploads/2/aa/uBk3axLIzZhikLo4w8ft74pA/image.png\"></a></div>",
        "id": 1414150,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659450760
    },
    {
        "content": "<p>Looks similar to <a href=\"#narrow/stream/3-backend/topic/error.3A.20.22Timed.20out.20after.2030.20seconds.20processing.201.20events.22\">https://chat.zulip.org/#narrow/stream/3-backend/topic/error.3A.20.22Timed.20out.20after.2030.20seconds.20processing.201.20events.22</a></p>",
        "id": 1414151,
        "sender_full_name": "Aman (amanagr)",
        "timestamp": 1659451201
    },
    {
        "content": "<p>I think this is likely unrelated -- that one is about image previews when the third-party site is slow, and I believe is fixed.</p>",
        "id": 1414293,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659477848
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"20576\">@Cosmic Sound</span> so, the exception you see is a timeout doing an extremely inexpensive query (~1ms typically) to write some \"last time this user did this API request\" data.</p>",
        "id": 1414294,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659477919
    },
    {
        "content": "<p>I don't have a good theory for what might cause that other than some sort of networking interruption between your Zulip server and your database, or the database having a deadlock or something.</p>",
        "id": 1414296,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659477958
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"7\">@Tim Abbott</span> is there something we can do to debug this? In past week got like 7 such emails, yet they all differ a bit on the template used to report the errors.</p>",
        "id": 1414482,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659528188
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"20576\">@Cosmic Sound</span> well, to start, can you talk about what sort of network you're running Zulip under? I can imagine something you're doing on your infrastructure, like \"It's a virtualization system that freezes the machine for 1 minute periodically to do backups\", for example, triggering this notification if it happened in the middle of the request.</p>",
        "id": 1414605,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659555600
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"7\">@Tim Abbott</span> we run on proxmox with KVM machines. Will check if backups were running at thise times. Yet we do run backups at night only. We also use ceph storage with NVM so our storage is very fast. Network its 1 gb vlan and 1 gb external from OVH.</p>",
        "id": 1415055,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659622024
    },
    {
        "content": "<p>Could it be RAM usage? I had the machine run with 4 GB, now I increased to 6 GB, and I see over 4 used.</p>",
        "id": 1415081,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659624272
    },
    {
        "content": "<div class=\"codehilite\" data-code-language=\"logger\"><pre><span></span><code>Error generated by Anonymous user (not logged in) on chat deployment\n\nTraceback (most recent call last):\n File \"/home/zulip/deployments/2022-08-01-19-55-31/zerver/management/commands/process_queue.py\", line 24, in log_and_exit_if_exception\n   yield\n File \"/home/zulip/deployments/2022-08-01-19-55-31/zerver/management/commands/process_queue.py\", line 106, in handle\n   worker.setup()\n File \"/home/zulip/deployments/2022-08-01-19-55-31/zerver/worker/queue_processors.py\", line 398, in setup\n   self.q = SimpleQueueClient(prefetch=self.PREFETCH)\n File \"/home/zulip/deployments/2022-08-01-19-55-31/zerver/lib/queue.py\", line 44, in __init__\n   self._connect()\n File \"/home/zulip/deployments/2022-08-01-19-55-31/zerver/lib/queue.py\", line 142, in _connect\n   self.connection = pika.BlockingConnection(self._get_parameters())\n File \"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py\", line 360, in __init__\n   self._impl = self._create_connection(parameters, _impl_class)\n File \"/srv/zulip-venv-cache/b9b6b1e1f9bff55507160d19f5d4e646428ecb02/zulip-py3-venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py\", line 451, in _create_connection\n   raise self._reap_last_connection_workflow_error(error)\npika.exceptions.AMQPConnectionError\n\n\nDeployed code:\n- git: 6.0-dev-1177-gf2a3236b42\n- ZULIP_VERSION: 6.0-dev-1177-gf2a3236b42\n\n\nRequest info: none```\n</code></pre></div>",
        "id": 1415095,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659627520
    },
    {
        "content": "<p>looking at dates are old</p>",
        "id": 1415098,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659627614
    },
    {
        "content": "<p>i received this one above last</p>",
        "id": 1415099,
        "sender_full_name": "Cosmic Sound",
        "timestamp": 1659627623
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"20576\">@Cosmic Sound</span> that last one is usually what happens when you restart RabbitMQ (and thus Zulip experiences it as down for a bit); it's not of interest if it's not continuing, as presumably your RabbitMQ server restarted properly.</p>",
        "id": 1415241,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659640589
    },
    {
        "content": "<p>I don't see a clear reason that RAM usage would cause this sort of timeout in a write to the database that would typically take about a millisecond, but I can't rule it out in a virtualization environment.</p>",
        "id": 1415243,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1659640634
    }
]