[
    {
        "content": "<p>Hey all. I am trying the docker install behind a reverse proxy. I've followed the instructions <a href=\"https://zulip.readthedocs.io/en/latest/production/deployment.html#configuring-zulip-to-trust-proxies\">here</a> and i get to the point where i need to restart the server. But when I run <code>sudo -u zulip /home/zulip/deployments/current/scripts/restart-server</code>, I get the following error:</p>\n<div class=\"codehilite\"><pre><span></span><code>2023-09-04 22:54:22,744 restart-server: Running syntax and database checks\nTraceback (most recent call last):\n  File &quot;./manage.py&quot;, line 144, in &lt;module&gt;\n    log_management_command(sys.argv, settings.MANAGEMENT_LOG_PATH)\n  File &quot;/srv/zulip-venv-cache/3ad8fd7ddf0d2634f7288bf690ece70f8cbe4ba5/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py&quot;, line 102, in __getattr__\n    self._setup(name)\n  File &quot;/srv/zulip-venv-cache/3ad8fd7ddf0d2634f7288bf690ece70f8cbe4ba5/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py&quot;, line 89, in _setup\n    self._wrapped = Settings(settings_module)\n  File &quot;/srv/zulip-venv-cache/3ad8fd7ddf0d2634f7288bf690ece70f8cbe4ba5/zulip-py3-venv/lib/python3.8/site-packages/django/conf/__init__.py&quot;, line 217, in __init__\n    mod = importlib.import_module(self.SETTINGS_MODULE)\n  File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 848, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/home/zulip/deployments/2023-08-25-19-03-42/zproject/settings.py&quot;, line 27, in &lt;module&gt;\n    from .computed_settings import *  # noqa: F403 isort: skip\n  File &quot;/home/zulip/deployments/2023-08-25-19-03-42/zproject/computed_settings.py&quot;, line 74, in &lt;module&gt;\n    SECRET_KEY = get_mandatory_secret(&quot;secret_key&quot;)\n  File &quot;/home/zulip/deployments/2023-08-25-19-03-42/zproject/config.py&quot;, line 50, in get_mandatory_secret\n    raise ZulipSettingsError(f&#39;Mandatory secret &quot;{key}&quot; is not set&#39;)\nzproject.config.ZulipSettingsError: Mandatory secret &quot;secret_key&quot; is not set\nTraceback (most recent call last):\n  File &quot;/home/zulip/deployments/current/scripts/restart-server&quot;, line 47, in &lt;module&gt;\n    subprocess.check_call([&quot;./manage.py&quot;, &quot;check&quot;, &quot;--database&quot;, &quot;default&quot;])\n  File &quot;/usr/lib/python3.8/subprocess.py&quot;, line 364, in check_call\n    raise CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command &#39;[&#39;./manage.py&#39;, &#39;check&#39;, &#39;--database&#39;, &#39;default&#39;]&#39; returned non-zero exit status 1.\n</code></pre></div>\n<p>seems to me that because the docker container started with passing in settings, running it on the command line from within the docker container is not getting those passed variables ... but i am guessing. if that's the case, am wondering if i can't pass in the trusted proxies IP from the compose file.</p>\n<p>any ideas?</p>",
        "id": 1635022,
        "sender_full_name": "fyrfli",
        "timestamp": 1693886687
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"27689\">@fyrfli</span> If this is in docker, are you using our docker project <a href=\"https://github.com/zulip/docker-zulip\">https://github.com/zulip/docker-zulip</a>?</p>",
        "id": 1635088,
        "sender_full_name": "Mateusz Mandera",
        "timestamp": 1693915302
    },
    {
        "content": "<p>yep, did i miss something in the instructions? let me re-read.</p>",
        "id": 1635128,
        "sender_full_name": "fyrfli",
        "timestamp": 1693926638
    },
    {
        "content": "<p>yep. missed it. think i got it sorted. thanks for the reminder to RTFM. <span aria-label=\"wink\" class=\"emoji emoji-1f609\" role=\"img\" title=\"wink\">:wink:</span></p>",
        "id": 1635161,
        "sender_full_name": "fyrfli",
        "timestamp": 1693932289
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"27689\">fyrfli</span> has marked this topic as resolved.</p>",
        "id": 1635162,
        "sender_full_name": "Notification Bot",
        "timestamp": 1693932296
    }
]