[
    {
        "content": "<p>i have upgraded from 2.0.8 to 2.1.1, it seems the Google OAuth redirect uri has changed. previously its <code>https://zulip.example.com/accounts/login/google/done/</code> but now its redirecting to <code>https://zulip.example.com/complete/google/</code>. is this change intentional,  i dont see its documented even in <code>zproject/prod_settings_template.py</code>?</p>",
        "id": 802975,
        "sender_full_name": "Andhie Wong",
        "timestamp": 1576502116
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"13626\">@Andhie Wong</span> Yes, it's a result of us changing the library on which we build the backend to <code>python-social-auth</code>.</p>",
        "id": 802983,
        "sender_full_name": "Mateusz Mandera",
        "timestamp": 1576509418
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"13626\">@Andhie Wong</span> thanks for the report!  This is indeed an oversight in our documentation updates.</p>\n<p><span class=\"user-mention\" data-user-id=\"10349\">@Mateusz Mandera</span> I think this means we have a bug in our documentation, because <code>prod_settings_template.py</code> has:</p>\n<div class=\"codehilite\"><pre><span></span># (3) Return to &quot;Credentials&quot;, and select &quot;Create credentials&quot;.\n# Choose &quot;OAuth client ID&quot;, and follow prompts to create a consent\n# screen.  Fill in &quot;Authorized redirect URIs&quot; with a value like\n#   https://zulip.example.com/accounts/login/google/done/\n# based on your value for EXTERNAL_HOST.\n</pre></div>\n\n\n<p>(And we should audit for other places, and update the \"upgrade notes\").</p>",
        "id": 803049,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1576537258
    }
]