[
    {
        "content": "<p>Hi, I am using Zulip on Droplet server. I upgraded Ubuntu and now my entire server has crashed. We are a fully voluntary non-profit organisation using Zulip to communicate with all of our volunteers and I am clearly out of my depth! Should I revert back to backup from 6 days ago?</p>\n<div class=\"codehilite\"><pre><span></span><code>root@Rocket-Chat:~# supervisorctl status\ngo-camo                                                         RUNNING   pid 974, uptime 0:03:58\nprocess-fts-updates                                             FATAL     Exited too quickly (process log may have details)\nsmokescreen                                                     RUNNING   pid 975, uptime 0:03:58\nzulip-django                                                    FATAL     Exited too quickly (process log may have details)\nzulip-tornado                                                   FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_deferred_work                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_digest_emails                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_email_mirror                         FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_email_senders                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_embed_links                          FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_embedded_bots                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_error_reports                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_invites                              FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_missedmessage_emails                 FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_missedmessage_mobile_notifications   FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_outgoing_webhooks                    FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_user_activity                        FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_user_activity_interval               FATAL     Exited too quickly (process log may have details)\nzulip-workers:zulip_events_user_presence                        FATAL     Exited too quickly (process log may have details)\nzulip_deliver_scheduled_emails                                  FATAL     Exited too quickly (process log may have details)\nzulip_deliver_scheduled_messages                                FATAL     Exited too quickly (process log may have details)\n</code></pre></div>",
        "id": 1629638,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692743161
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>root@Rocket-Chat:~# rm -rf /srv/zulip-venv-cache/*\n/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2 \\\n    /home/zulip/deployments/current/ --ignore-static-assets --audit-fts-indexes\n2023-08-22 22:47:02,720 upgrade-zulip-stage-2: Upgrading from 7.2 to 7.2, in /home/zulip/deployments/current/\nTraceback (most recent call last):\n  File &quot;/home/zulip/deployments/2023-07-22-15-34-26/../current/manage.py&quot;, line 12, in &lt;module&gt;\n    setup_path()\n  File &quot;/home/zulip/deployments/2023-07-22-15-34-26/scripts/lib/setup_path.py&quot;, line 14, in setup_path\n    with open(activate_this) as f:\nFileNotFoundError: [Errno 2] No such file or directory: &#39;/home/zulip/deployments/2023-07-22-15-34-26/zulip-py3-venv/bin/activate_this.py&#39;\nTraceback (most recent call last):\n  File &quot;/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2&quot;, line 212, in &lt;module&gt;\n    django_pg_version = subprocess.check_output(\n  File &quot;/usr/lib/python3.10/subprocess.py&quot;, line 421, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File &quot;/usr/lib/python3.10/subprocess.py&quot;, line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command &#39;[&#39;../current/manage.py&#39;, &#39;shell&#39;, &#39;-c&#39;, &#39;from django.db import connection; print(int(connection.cursor().connection.server_version/10000))&#39;]&#39; returned non-zero exit status 1.\n</code></pre></div>",
        "id": 1629649,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692744457
    },
    {
        "content": "<p>Can I put a bounty on resolving this issue?</p>",
        "id": 1629651,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692744551
    },
    {
        "content": "<p>Thanks for copy-pasting all that! I'm sorry that you've run into this while investigating an issue with notifications. (I recognize your name from the email support thread.)</p>\n<p>This isn't my area, but the \"No such file or directory\" line looks like a match for this issue: <a href=\"https://github.com/zulip/zulip/issues/26338\">zulip/zulip#26338</a>.</p>",
        "id": 1629730,
        "sender_full_name": "Chris Bobbe",
        "timestamp": 1692749348
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"27597\">@Daniel Hammocks</span> you shouldn't need to revert to backup, just a sec.</p>",
        "id": 1629736,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1692749724
    },
    {
        "content": "<p>I expect you just need to run the remaining steps from these instructions: <a href=\"https://zulip.readthedocs.io/en/latest/production/upgrade.html#upgrading-the-operating-system\">https://zulip.readthedocs.io/en/latest/production/upgrade.html#upgrading-the-operating-system</a></p>",
        "id": 1629737,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1692749742
    },
    {
        "content": "<p>Well, do that, except also do <code>/home/zulip/deployments/current/scripts/upgrade-zulip-from-git 7.x</code> to get the fix to <a href=\"https://github.com/zulip/zulip/pull/26338\">#26338</a>, I think just before step 5.</p>",
        "id": 1629738,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1692749823
    },
    {
        "content": "<p>Thank you for your responses. I ran the following lines of code and none were successful.</p>\n<div class=\"codehilite\"><pre><span></span><code>/home/zulip/deployments/current/scripts/upgrade-zulip-from-git 7.x\n</code></pre></div>\n<p>I then realised the 7.x so I replaced it with 7.2</p>\n<div class=\"codehilite\"><pre><span></span><code>/home/zulip/deployments/current/scripts/upgrade-zulip-from-git 7.2\n</code></pre></div>\n<p>and that the GH help ticket suggested running</p>\n<div class=\"codehilite\"><pre><span></span><code>/home/zulip/deployments/current/scripts/lib/create-production-venv /home/zulip/deployments/current\n</code></pre></div>\n<p>Here is the result of Step 5 of the upgrade script which I was originally following.</p>\n<div class=\"codehilite\"><pre><span></span><code>root@Rocket-Chat:~# rm -rf /srv/zulip-venv-cache/*\n/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2 \\\n    /home/zulip/deployments/current/ --ignore-static-assets --audit-fts-indexes\n2023-08-23 01:36:46,646 upgrade-zulip-stage-2: Upgrading from 7.2 to 7.2, in /home/zulip/deployments/current/\nTraceback (most recent call last):\n  File &quot;/home/zulip/deployments/2023-07-22-15-34-26/../current/manage.py&quot;, line 12, in &lt;module&gt;\n    setup_path()\n  File &quot;/home/zulip/deployments/2023-07-22-15-34-26/scripts/lib/setup_path.py&quot;, line 14, in setup_path\n    with open(activate_this) as f:\nFileNotFoundError: [Errno 2] No such file or directory: &#39;/home/zulip/deployments/2023-07-22-15-34-26/zulip-py3-venv/bin/activate_this.py&#39;\nTraceback (most recent call last):\n  File &quot;/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2&quot;, line 212, in &lt;module&gt;\n    django_pg_version = subprocess.check_output(\n  File &quot;/usr/lib/python3.10/subprocess.py&quot;, line 421, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File &quot;/usr/lib/python3.10/subprocess.py&quot;, line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command &#39;[&#39;../current/manage.py&#39;, &#39;shell&#39;, &#39;-c&#39;, &#39;from django.db import connection; print(int(connection.cursor().connection.server_version/10000))&#39;]&#39; returned non-zero exit status 1.\n</code></pre></div>",
        "id": 1629774,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692754832
    },
    {
        "content": "<p>No, we do mean <code>7.x</code>, not <code>7.2</code>.</p>\n<p>But I think we can fix this without that upgrade.</p>",
        "id": 1629775,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1692754974
    },
    {
        "content": "<p>Do these as step 5:</p>\n<div class=\"codehilite\"><pre><span></span><code>rm -rf /srv/zulip-venv-cache/*\n/home/zulip/deployments/current/scripts/lib/create-production-venv /home/zulip/deployments/current\n/home/zulip/deployments/current/scripts/lib/upgrade-zulip-stage-2 \\\n    /home/zulip/deployments/current/ --ignore-static-assets --audit-fts-indexes\n</code></pre></div>",
        "id": 1629776,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1692754998
    },
    {
        "content": "<p>(<code>7.x</code> is the thing that will shortly be released as <code>7.3</code>, which has the fix for this, hence the suggestion to upgrade to that -- but I think that may run afoul of being halfway configured)</p>",
        "id": 1629777,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1692755060
    },
    {
        "content": "<p>And, in general, if a command is not successful, we're going to want to see <em>how</em> it wasn't successful. <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 1629778,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1692755104
    },
    {
        "content": "<p>That seemed to have worked! Amazing. Thank you. Thank you. Thank you. AND it seems to have fixed pushed notifications. THANK YOU! CAn I buy you guys a coffee or something please?</p>",
        "id": 1629779,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692755573
    },
    {
        "content": "<p>Interesting that it fixed push notifications -- that, I don't have any theories on, since the issue seemed to have been networking in some form, for you.</p>\n<p>You can drop something in <a href=\"https://github.com/sponsors/zulip\">https://github.com/sponsors/zulip</a> if you're so inclined (there's a non-recurring option tucked in there), but it's absolutely not necessary or expected.</p>",
        "id": 1629780,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1692755773
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"27597\">@Daniel Hammocks</span> Glad things are fixed! One thought on how the upgrade may have fixed the push notifications issue: the upgrade procedure will have included a restart of all the Zulip server processes. If one of those had gotten into a bad state somehow, then the restart could have fixed that.</p>\n<p>Given that we don't know of a relevant code change we've made recently that would have affected this, that restart seems fairly likely as the step that fixed the push notifications.</p>",
        "id": 1630252,
        "sender_full_name": "Greg Price",
        "timestamp": 1692820879
    },
    {
        "content": "<p>In general if your Zulip server is behaving in a bad way where it seems like a restart might get it back to working, you can always restart it with the <code>scripts/restart-server</code> script as described here:<br>\n<a href=\"https://zulip.readthedocs.io/en/latest/production/settings.html#making-changes\">https://zulip.readthedocs.io/en/latest/production/settings.html#making-changes</a></p>\n<p>(Though that <em>shouldn't</em> be necessary in general — it should only be needed when you've made some configuration change and need the server processes to pick up that change. So if you do find yourself repeatedly needing to do restarts outside that context, then we'd be interested in hearing about it so we can try to debug.)</p>",
        "id": 1630265,
        "sender_full_name": "Greg Price",
        "timestamp": 1692821062
    },
    {
        "content": "<p>@Greg I did try restarting all the services and then a full reboot of the server when I first started getting the error messages. As well as following the push notification guide to try and re-register the service. Not sure if that helps in any way? But I’m just glad it’s fixed. Thank you for all your help.</p>",
        "id": 1630278,
        "sender_full_name": "Daniel Hammocks",
        "timestamp": 1692821143
    },
    {
        "content": "<p>Hmm. That is informative ­— thanks for the update!</p>\n<p>I guess another thing is that you mentioned at the top of this thread that you were upgrading Ubuntu, the operating system. Did that perhaps involve rebooting the machine? Perhaps something was wedged at the system level, or otherwise outside of Zulip's own processes that <code>scripts/restart-server</code> restarts, and so the reboot is what unwedged it.</p>",
        "id": 1630292,
        "sender_full_name": "Greg Price",
        "timestamp": 1692821933
    }
]