[
    {
        "content": "<p>I tried ./manage.py sync_ldap_user_data and get the error-message that the user not found. I guess that the reason is pretty simple:<br>\nI choose to use sAMAccountName as identifier in login and get the fullname and email from Active-Directory.<br>\nThe sync seems to try a search using the email as search-criteria which can not work.<br>\nAny idea how to fix this?</p>",
        "id": 695128,
        "sender_full_name": "niels",
        "timestamp": 1549441668
    },
    {
        "content": "<p>Solved it with <a href=\"https://zulip.readthedocs.io/en/1.9.1/production/authentication-methods.html#multiple-ldap-searches\" target=\"_blank\" title=\"https://zulip.readthedocs.io/en/1.9.1/production/authentication-methods.html#multiple-ldap-searches\">https://zulip.readthedocs.io/en/1.9.1/production/authentication-methods.html#multiple-ldap-searches</a>.</p>",
        "id": 695158,
        "sender_full_name": "niels",
        "timestamp": 1549462444
    },
    {
        "content": "<p>Great, glad to hear the docs were helpful <span aria-label=\"slight smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"slight smile\">:slight_smile:</span></p>",
        "id": 695463,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1549482470
    }
]